<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KUCY2QTP01" name="com.PaymentCenterTestCases.PaymentCenterTestClass" tests="10" failures="5" timestamp="25 Apr 2016 06:54:45 GMT" time="711.462" errors="0">
  <testcase name="Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment" time="78.329" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Exception thrown, logout from KU Portal. Excep MsgExcep thrown. excep msg Autoposting failed expected [true] but found [false] expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from KU Portal. Excep MsgExcep thrown. excep msg Autoposting failed expected [true] but found [false] expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.Launch_PaymentCenter_From_KUPortal(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment -->
  <testcase name="Scenario_6_ForgotPassword" time="19.141" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_1_MakeCCPaymentwithPortalCredential" time="124.470" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Excep thrown. excep msg Autoposting failed expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Excep thrown. excep msg Autoposting failed expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.verifyPaymentInPaymentCenterdb(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_1_MakeCCPaymentwithPortalCredential(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_1_MakeCCPaymentwithPortalCredential -->
  <testcase name="Scenario_5_FeeTypePaymentFromEmployeeSite" time="127.361" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Payment Center return false, i.e some error occured expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Payment Center return false, i.e some error occured expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_5_FeeTypePaymentFromEmployeeSite(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_5_FeeTypePaymentFromEmployeeSite -->
  <testcase name="Scenario_10_EcheckEnableDisable" time="136.298" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Exception thrown , Excep msh : Timed out after 90 seconds waiting for presence of element located by: By.xpath: .//span[@id=&#039;ctl00_CPL_Main_ucStudentInfo_lblStudentID&#039;]
Build info: version: &#039;2.48.2&#039;, revision: &#039;41bccdd&#039;, time: &#039;2015-10-09 19:55:52&#039;
System info: host: &#039;KUCY2QTP01&#039;, ip: &#039;10.78.4.89&#039;, os.name: &#039;Windows 2003&#039;, os.arch: &#039;x86&#039;, os.version: &#039;5.2&#039;, java.version: &#039;1.7.0_80-ea&#039;
Session ID: 98fa06c8-189c-46af-861a-c756058f8844
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown , Excep msh : Timed out after 90 seconds waiting for presence of element located by: By.xpath: .//span[@id='ctl00_CPL_Main_ucStudentInfo_lblStudentID']
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'KUCY2QTP01', ip: '10.78.4.89', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_80-ea'
Session ID: 98fa06c8-189c-46af-861a-c756058f8844
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.EnableDisableECheckfromEmployeeSite(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_10_EcheckEnableDisable(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_10_EcheckEnableDisable -->
  <testcase name="Scenario_4_makeOnetimePaymentwithoutLogin" time="58.829" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_3_MakeECheck_PaymentwithPortalCredential" time="109.892" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Payment Center return false,some error occured expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Payment Center return false,some error occured expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_3_MakeECheck_PaymentwithPortalCredential(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_3_MakeECheck_PaymentwithPortalCredential -->
  <testcase name="Scenario_11_EmployeeSiteReports" time="40.329" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_9_SearchStudentInEmployeeSite" time="7.156" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_8_ChangePassword" time="9.657" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
</testsuite> <!-- com.PaymentCenterTestCases.PaymentCenterTestClass -->
